<?php
/**
 * Release build: merges src/*.php (via OC_Autoloader::classFiles) and every
 * public/*.php page into a single dist/app.php, so the CI release artifact
 * is one self-contained PHP file with no autoloading required at runtime.
 *
 * Pages are merged as callable sections dispatched by a tiny front
 * controller appended at the end, keyed off the request path.
 */
declare(strict_types=1);

require_once __DIR__ . '/src/Autoloader.php';

$srcDir = __DIR__ . '/src';
$publicDir = __DIR__ . '/public';
$outDir = __DIR__ . '/dist';

if (!is_dir($outDir)) {
    mkdir($outDir, 0775, true);
}

$out = "<?php\n// Generated by build.php — merged single-file build. Do not edit by hand.\n\n";

foreach (OC_Autoloader::classFiles($srcDir) as $file) {
    $out .= strip_leading_php_tag(file_get_contents($file)) . "\n";
}

$out .= "// ---- front controller -----------------------------------------\n";
$out .= "OC_Env::load(__DIR__ . '/.env');\n";
$out .= "\$__routes = [];\n";

foreach (glob($publicDir . '/*.php') as $file) {
    if (basename($file) === 'bootstrap.php') {
        continue;
    }
    $route = basename($file, '.php');
    $body = strip_leading_php_tag(file_get_contents($file));
    // bootstrap.php require is unnecessary in the merged build; strip it.
    $body = preg_replace('/^\s*require(_once)?\s+__DIR__\s*\.\s*\'\/bootstrap\.php\';\s*$/m', '', $body);
    // $body already opens in PHP-code mode (its leading <?php was stripped)
    // and manages its own <?php/?> transitions for inline HTML, so it must
    // be concatenated directly — wrapping it in ?> ... <?php would dump its
    // leading PHP statements (auth checks, data fetch) as literal text.
    $out .= "\$__routes['{$route}'] = function () {\n{$body}\n};\n";
}

$out .= <<<'PHP'
$__uri = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);
$__page = trim($__uri, '/');
$__page = $__page === '' ? 'index' : basename($__page, '.php');
if (!isset($__routes[$__page])) {
    $__page = 'index';
}
$__routes[$__page]();
PHP;

file_put_contents($outDir . '/app.php', $out);
fwrite(STDOUT, "Built dist/app.php\n");

function strip_leading_php_tag(string $code): string
{
    return preg_replace('/^<\?php\s*/', '', $code, 1);
}
